//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DB
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(HomeProperty_GalleriesMetaData))]
    public partial class HomeProperty_Galleries
    {
        public int GalleryID { get; set; }
        public int HomePropertyID { get; set; }
        public string ImageName { get; set; }
        public string ImageTitle { get; set; }
    
        public virtual HomeProperty HomeProperty { get; set; }
    }
}
