//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DB
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(PropertyViewMetaData))]
    public partial class PropertyView
    {
        public int PropertyViewID { get; set; }
        public int HomePropertyID { get; set; }
        public System.DateTime PropertyViewDate { get; set; }
        public int PropertyViewCount { get; set; }
        public string StringDate { get; set; }
    
        public virtual HomeProperty HomeProperty { get; set; }
    }
}
