//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DB
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(StateSiteMetaData))]
    public partial class StateSite
    {
        public int StateSiteID { get; set; }
        public System.DateTime StateSiteDate { get; set; }
        public int StateSiteCount { get; set; }
    }
}
