// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace RealStateProject.Controllers
{
    public partial class PropertyController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PropertyController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PropertyController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PropertyController Actions { get { return MVC.Property; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Property";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Property";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string ShowAllProperty = "ShowAllProperty";
            public readonly string ShowDetailProperty = "ShowDetailProperty";
            public readonly string PapulerProperty = "PapulerProperty";
            public readonly string NearbyProperty = "NearbyProperty";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string ShowAllProperty = "ShowAllProperty";
            public const string ShowDetailProperty = "ShowDetailProperty";
            public const string PapulerProperty = "PapulerProperty";
            public const string NearbyProperty = "NearbyProperty";
        }


        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string NearbyProperty = "NearbyProperty";
                public readonly string PapulerProperty = "PapulerProperty";
                public readonly string ShowAllProperty = "ShowAllProperty";
                public readonly string ShowDetailProperty = "ShowDetailProperty";
            }
            public readonly string NearbyProperty = "~/Views/Property/NearbyProperty.cshtml";
            public readonly string PapulerProperty = "~/Views/Property/PapulerProperty.cshtml";
            public readonly string ShowAllProperty = "~/Views/Property/ShowAllProperty.cshtml";
            public readonly string ShowDetailProperty = "~/Views/Property/ShowDetailProperty.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PropertyController : RealStateProject.Controllers.PropertyController
    {
        public T4MVC_PropertyController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ShowAllPropertyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowAllProperty()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowAllProperty);
            ShowAllPropertyOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ShowDetailPropertyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowDetailProperty()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowDetailProperty);
            ShowDetailPropertyOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PapulerPropertyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PapulerProperty()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PapulerProperty);
            PapulerPropertyOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NearbyPropertyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult NearbyProperty()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NearbyProperty);
            NearbyPropertyOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
