// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace RealStateProject.Areas.UserPanel.Controllers
{
    public partial class PropertyController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PropertyController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PropertyController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PropertyController Actions { get { return MVC.UserPanel.Property; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "UserPanel";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Property";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Property";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Create = "Create";
            public readonly string testCreate = "testCreate";
            public readonly string testCreate2 = "testCreate2";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Create = "Create";
            public const string testCreate = "testCreate";
            public const string testCreate2 = "testCreate2";
        }


        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create
        {
            public readonly string _homeProperty = "_homeProperty";
        }
        static readonly ActionParamsClass_testCreate s_params_testCreate = new ActionParamsClass_testCreate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_testCreate testCreateParams { get { return s_params_testCreate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_testCreate
        {
            public readonly string _createPropertyViewModel = "_createPropertyViewModel";
            public readonly string City = "City";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Create = "Create";
                public readonly string testCreate = "testCreate";
            }
            public readonly string Create = "~/Areas/UserPanel/Views/Property/Create.cshtml";
            public readonly string testCreate = "~/Areas/UserPanel/Views/Property/testCreate.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PropertyController : RealStateProject.Areas.UserPanel.Controllers.PropertyController
    {
        public T4MVC_PropertyController() : base(Dummy.Instance) { }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            CreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, DataLayer.DB.HomeProperty _homeProperty);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create(DataLayer.DB.HomeProperty _homeProperty)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "_homeProperty", _homeProperty);
            CreateOverride(callInfo, _homeProperty);
            return callInfo;
        }

        [NonAction]
        partial void testCreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult testCreate()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.testCreate);
            testCreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void testCreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, DataLayer.ViewModels.CreatePropertyViewModel _createPropertyViewModel, int City);

        [NonAction]
        public override System.Web.Mvc.ActionResult testCreate(DataLayer.ViewModels.CreatePropertyViewModel _createPropertyViewModel, int City)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.testCreate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "_createPropertyViewModel", _createPropertyViewModel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "City", City);
            testCreateOverride(callInfo, _createPropertyViewModel, City);
            return callInfo;
        }

        [NonAction]
        partial void testCreate2Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult testCreate2()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.testCreate2);
            testCreate2Override(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
