//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer.DB
{
    public class HomeProperty_StatusMetaData
    {
        [Key]
        public int PropertyStatusID { get; set; }

        [Display(Name = "وضعیت آگهی")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string StatusTitle { get; set; }

        [Display(Name = " کد وضعیت ")]
        public string StatusCode { get; set; }
    }
}