//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;

namespace DataLayer.DB
{
    public class RigionMetaData
    {
        [Key]
        public int RigionID { get; set; }
        public int CityID { get; set; }

        [Display(Name = "محل آگهی")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string RegionTitle { get; set; }

        [Display(Name = "کد محل آگهی ")]
        public string RegionCode { get; set; }

    }
}