//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace DataLayer.DB
{
    public class StateSiteMetaData
    {
        [Key]
        public int StateSiteID { get; set; }

        [Display(Name = "تاریخ بازدید")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public System.DateTime StateSiteDate { get; set; }

        [Display(Name = "تعداد بازدید")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int StateSiteCount { get; set; }
    }
}