//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using DataLayer;
 

namespace DataLayer.DB
{
    public class UserMetaData
    {
        [Key]
        public int UserID { get; set; }


        [Display(Name = "RoleID", ResourceType = typeof(Resources.Resource_User))]
        public int RoleID { get; set; }

        [Display(Name = "CultureID", ResourceType = typeof(Resources.Resource_User))]
        public int CultureID { get; set; }

        [Display(Name ="UserName",ResourceType = typeof(Resources.Resource_User) )]
        [Required(ErrorMessageResourceType = typeof(Resources.Resource_User),ErrorMessageResourceName = "RequiredUserName")]
        public string UserName { get; set; }

        [EmailAddress(ErrorMessageResourceType =typeof(Resources.Resource_Main),ErrorMessageResourceName ="EmailFormat")]
        [Display(Name = "Email", ResourceType = typeof(Resources.Resource_User))]
        [Required(ErrorMessageResourceType = typeof(Resources.Resource_User), ErrorMessageResourceName = "RequiredUserEmail")]
        public string Email { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Password", ResourceType = typeof(Resources.Resource_User))]
        [Required(ErrorMessageResourceType = typeof(Resources.Resource_User), ErrorMessageResourceName = "RequiredUserPassword")]
        public string Password { get; set; }

        [Display(Name = "ActiveCode", ResourceType = typeof(Resources.Resource_User))]
        public string ActiveCode { get; set; }

        [Display(Name = "IsActive", ResourceType = typeof(Resources.Resource_User))]
        public Nullable<bool> IsActive { get; set; }

        [Display(Name = "RegisterDate", ResourceType = typeof(Resources.Resource_User))]
        public Nullable<System.DateTime> RegisterDate { get; set; }

        
    }
}